#!/usr/bin/env sh

# Colores
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Inicia el gancho de pre-commit de Husky
. "$(dirname -- "$0")/_/husky.sh"

echo "${YELLOW}Running pre-commit hook${NC}"
pnpm run format:fix
echo "---------------------"
echo "${YELLOW}Running lint:fix${NC}"
pnpm run lint:fix
echo "---------------------"
echo "${YELLOW}Running commitlint${NC}"
pnpm commitlint --edit "$1"
echo "${GREEN}Pre-commit hook completed successfully${NC}"